name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List tags
        run: git tag

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag | tail -n 1)
          echo "::set-output name=latest::$latest_tag"

      - name: Increment version
        id: increment_version
        run: |
          # Извлечь текущий тег
          current_tag="${{ steps.get_latest_tag.outputs.latest }}"
          echo "Current tag is: $current_tag"

          # Парсинг тега
          IFS='.' read -r major minor patch <<< "${current_tag#v}"
          
          # Инкрементирование патч-версии
          patch=$((patch + 1))
          
          # Создание нового тега
          new_tag="v$major.$minor.$patch"
          echo "New tag will be: $new_tag"

          # Установка нового тега в выход
          echo "::set-output name=new_tag::$new_tag"

      - name: Create a new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag="${{ steps.increment_version.outputs.new_tag }}"
          
          # Настройка имени пользователя и электронной почты
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Создание нового тега
          git tag $new_tag
          
          # Пуш нового тега с использованием токена
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/breezeframework/breeze_data.git $new_tag


      - name: Print new tag
        run: |
          echo "Created new tag: ${{ steps.increment_version.outputs.new_tag }}"
