name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Загружает все теги и историю коммитов

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          if [ -z "$latest_tag" ]; then
            echo "No tags found. Starting from v0.1.0."
            latest_tag="v0.1.0"
          fi
          echo "Latest tag is: $latest_tag"
          echo "latest=$latest_tag" >> $GITHUB_ENV

      - name: Increment the version
        id: increment_version
        run: |
          tag_without_v="${{ env.latest }}"
          major=${tag_without_v%%.*}
          minor=${tag_without_v#*.}
          minor=${minor%%.*}
          patch=${tag_without_v##*.}
          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"
          echo "New tag will be: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Set up Git
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push new tag
        run: |
            git tag ${{ env.new_tag }}
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/breezeframework/breeze_data.git ${{ env.new_tag }}