name: Increment and Push Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is: $latest_tag"
          echo "::set-output name=latest::$latest_tag"

      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.get_latest_tag.outputs.latest }}"
          new_patch=$((patch + 1))
          new_tag="${major}.${minor}.${new_patch}"
          echo "New tag is: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create new tag
        run: |
          echo "Creating new tag: ${{ steps.increment_version.outputs.new_tag }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.increment_version.outputs.new_tag }}
          git push git@github.com:breezeframework/breeze_data.git ${{ steps.increment_version.outputs.new_tag }}
